AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Reward-Service-Deployment-Descriptor

Parameters:
  Stage:
    Type: String
    Description: Stage name to deploy resources to
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Runtime: java11
    MemorySize: 1024
    Timeout: 20
    AutoPublishAlias: !Ref Stage
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    CodeUri: ./application
    Tags:
      Stage: !Ref Stage
      Service: Reward
      Resource: Lambda
    Environment:
      Variables:
        TABLE: !Ref RewardTable
        APPLICATION_ENVIRONMENT: !Ref Stage
        CLOUD_REGION: us-east-1
        MAIN_CLASS: com.tekcapsule.reward.application.RewardApplication
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:

  # Setup API Gateway

  RewardApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "reward-${Stage}"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'X-Forwarded-For, Content-Type, Authorization, X-User-Login, X-Channel-Code'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: false
      Variables:
        LAMBDA_ALIAS: !Ref Stage

  # Setup DynamoDB Table

  RewardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Stage}Reward"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: lifetimeRewardPoints
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: lifetimeRewardPoints
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  # Setup Lambda Functions

  AwardPointsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Reward-AwardPoints"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RewardTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: awardPointsFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: reward/awardPoints
            Method: post
            RestApiId:
              Ref: RewardApi

  RedeemPointsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Reward-RedeemPoints"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RewardTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: redeemPointsFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: reward/redeemPoints
            Method: post
            RestApiId:
              Ref: RewardApi

  GetPointsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Reward-GetPoints"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RewardTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getPoints
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: reward/getPoints
            Method: post
            RestApiId:
              Ref: RewardApi

  GetLeaderboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Reward-GetLeaderboard"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RewardTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getLeaderboardFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: reward/getLeaderboard
            Method: post
            RestApiId:
              Ref: RewardApi


  # Set Output Variable

Outputs:
  ApiEndpoint:
    Description: "Reward API endpoint."
    Value: !Sub "https://${RewardApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/reward"
